# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository:  DYNAMIC_TAG 
  pullSecret: regsecret
  #pullPolicy: Never
resources: 
 limits:
  cpu: DYNAMIC_CPUMAX
  memory: DYNAMIC_MEMORYMAX
 request:
   cpu: DYNAMIC_CPUMIN
  memory: DYNAMIC_MEMORYMIN
  
